version: '3.1'

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 56111:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
