[package]
name = "rest"
version = "0.1.0"
authors = ["Mykola Basov <git@mbasov.com>"]
edition = "2018"

[dependencies]
conduit = { path = "../conduit" }
server = { path = "../server" }

serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
