[package]
name = "rwa_api"
version = "0.1.0"
authors = ["Mykola Basov <git@mbasov.com>"]
edition = "2018"

[workspace]
members = [
  "conduit",
  "rest_api",
]

[dependencies]
async-std = { version = "1.6", features = ["attributes"] }
anyhow = "1.0"
listenfd = "0.3.3"
conduit = { path = "./conduit" }
rest_api = { path = "./rest_api" }
